apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: chatterly-dev
  labels:
    app: api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z postgres-svc 5432; do
            echo "waiting for postgres ..."
            sleep 3
          done
          echo "Postgres is ready"
      - name: wait-for-redis
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z redis-svc 6379; do
            echo "waiting for redis ..."
            sleep 3
          done
          echo "Redis is ready"
      - name: run-migrations
        image: osmankhandev/chatterly-api:latest
        command:
        - sh
        - -c
        - npx prisma migrate deploy --schema=./prisma/schema.prisma
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: DATABASE_URL

      containers:
      - name: api
        image: osmankhandev/chatterly-api:latest
        imagePullPolicy: Always

        envFrom:
        - configMapRef:
            name: chatterly-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: DATABASE_URL

        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: REDIS_URL
        - name: JWT_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: JWT_ACCESS_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: JWT_REFRESH_SECRET
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chatterly-secrets
              key: POSTGRES_PASSWORD
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
