trigger:
- main
- development

pr:
- main
- development

pool:
  name: 'chatterly-ec2-agent-8gb'
stages:
- stage: Build
  jobs:
  - job: BuildAPIProject
    displayName: 'Build Chatterlys API Project'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
    - script: npm ci
      displayName: 'Install Dependencies'

    - script: npx prisma generate --schema=apps/api/prisma/schema.prisma
      displayName: 'Prisma Generate'

    - script: npx nx affected --target=build --base=origin/development --head=HEAD
      displayName: 'Build Affected Apps Like API In this Time'

    - script: |
        docker build -t chatterly-api:$(Build.BuildId) -f apps/api/Dockerfile .
      displayName: 'Docker Build'
