version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: chatterly_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatterly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  server:
    build: ./server
    container_name: chatterly_server
    restart: always
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/chatterly
    volumes:
      - ./server:/app
    command: npm run dev

volumes:
  pgdata:
