parameters:
  - name: dockerImage
    type: string
    default: ''
  - name: trivySeverity
    type: string
    default: 'HIGH, CRITICAL'
  - name: exitCodes
    type: string
    default: '1, 2'
  - name: runTrivy
    type: boolean
    default: true
  - name: acrName
    type: string
    default: 'acrchatterlydev'

steps:
  - script: |

      if ! command -v trivy >/dev/null 2>&1; then
        echo "Trivy not found, installing..."
        sudo curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      else
        echo "Trivy is already installed."
      fi
      
      trivy --version

      trivy image --severity ${{parameters.trivySeverity}} --exit-code ${{parameters.exitCodes}} --no-progress ${{parameters.dockerImage}}
    displayName: 'Trivy Scan for ${{parameters.dockerImage}}'
    continueOnError: false
  

