{{- if not .Values.monitoring.secretProviderClass.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: chatterly-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.localSecrets.DATABASE_URL | quote }}
  POSTGRES_USER: {{ .Values.localSecrets.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.localSecrets.POSTGRES_PASSWORD | quote }}
  REDIS_URL: {{ .Values.localSecrets.REDIS_URL | quote }}
  POSTGRES_DB: {{ .Values.localSecrets.POSTGRES_DB | quote }}
  PORT: {{ .Values.localSecrets.PORT | quote }}

  LOG_LEVEL: {{ .Values.localSecrets.LOG_LEVEL | quote }}
  JWT_ACCESS_SECRET: {{ .Values.localSecrets.JWT_ACCESS_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ .Values.localSecrets.JWT_REFRESH_SECRET | quote }}
  JWT_ACCESS_EXPIRE: {{ .Values.localSecrets.JWT_ACCESS_EXPIRE | quote }}
  JWT_REFRESH_EXPIRE: {{ .Values.localSecrets.JWT_REFRESH_EXPIRE | quote }}

  EMAIL_HOST: {{ .Values.localSecrets.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ .Values.localSecrets.EMAIL_PORT | quote }}
  EMAIL_USER: {{ .Values.localSecrets.EMAIL_USER | quote }}
  EMAIL_PASS: {{ .Values.localSecrets.EMAIL_PASS | quote }}
  EMAIL_FROM: {{ .Values.localSecrets.EMAIL_FROM | quote }}

  TWILIO_ACCOUNT_SSID: {{ .Values.localSecrets.TWILIO_ACCOUNT_SSID | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.localSecrets.TWILIO_AUTH_TOKEN | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.localSecrets.TWILIO_PHONE_NUMBER | quote }}
  TWILIO_RECOVERY_NUMBER: {{ .Values.localSecrets.TWILIO_RECOVERY_NUMBER | quote }}
{{- end -}}
