apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chatterly-kv-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{.Values.keyVault.identityClientId}}
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects: |-
      array:
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: redis-url
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectType: secret
        - |
          objectName: jwt-refresh-secret
          objectType: secret
        - |
          objectName: email-user
          objectType: secret
        - |
          objectName: email-pass
          objectType: secret
        - |
          objectName: twilio-account-ssid
          objectType: secret
        - |
          objectName: twilio-auth-token
          objectType: secret
        - |
          objectName: twilio-recovery-number
          objectType: secret
  secretObjects:
  - secretName: chatterly-secrets
    type: Opaque
    data:
    - objectName: postgres-user
      key: POSTGRES_USER
    - objectName: postgres-password
      key: POSTGRES_PASSWORD
    - objectName: database-url
      key: DATABASE_URL
    - objectName: redis-url
      key: REDIS_URL
    - objectName: jwt-access-secret
      key: JWT_ACCESS_SECRET
    - objectName: jwt-refresh-secret
      key: JWT_REFRESH_SECRET
    - objectName: email-user
      key: EMAIL_USER
    - objectName: email-pass
      key: EMAIL_PASS
    - objectName: twilio-account-ssid
      key: TWILIO_ACCOUNT_SSID
    - objectName: twilio-auth-token
      key: TWILIO_AUTH_TOKEN
    - objectName: twilio-recovery-number
      key: TWILIO_RECOVERY_NUMBER