apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatterly-api
  namespace: {{.Values.namespace}}
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{.Values.namespace}}
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  
    
