# Global Environment Variables

namespace: chatterly-dev
environment: dev

# API-service

api:
  image:
    repository: acrchatterlydev.azurecr.io/chatterly-api
    tag: latest
    pullPolicy: Always

  replicas: 1
  port: 3001
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"

    limits:
      memory: "512Mi"
      cpu: "500m"
  health:
    readiness:
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 30

# Postgres-DB
postgres:
  image: postgres:16-alpine
  storage: 1Gi
  storageClass: managed-csi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Redis-Cache
redis:
  image: redis:7-alpine
  storage: 1Gi
  storageClass: managed-csi
  maxmemory: 256mb
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

# Ingress

ingress:
  enabled: true
  className: nginx
  host: ""

# secrets

keyVault:
  enabled: true
  name: kv-chatterly-dev
  tenantId: 229929b3-9d7d-48ef-b948-b175d426ee74
  identityClientId: 0cc634fd-dba5-4e58-b816-44850fed678b
