localSecrets:
  # Development Environment Variables
  DATABASE_URL: "postgres://postgres:postgres@postgres-svc.chatterly-dev.svc.cluster.local:5432/chatterly"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  REDIS_URL: "redis://redis-svc.chatterly-dev.svc.cluster.local:6379"
  POSTGRES_DB: "chatterly"
  PORT: "3001"

  LOG_LEVEL: "debug"
  JWT_ACCESS_SECRET: "bc1a992c62dbb3e25ef997d390e56fcd490ef82591a54257e5b4f4aec2309c7f80c62816abff1725d532a63b79ed9ad215c1144c4a4e707578dd137290eb7b79"
  JWT_REFRESH_SECRET: "64288c19b93829bf4e57af2dd09f65603c0bdd3e53b1abcd5a05e45460d7223bb3ca93442d230543c10f2ff69cbb18fb8063c88afed3fc950a0feb872d8c8d9f"
  JWT_ACCESS_EXPIRE: "15m"
  JWT_REFRESH_EXPIRE: "7d"
  # Email/SMTP Configuration
  EMAIL_HOST: "sandbox.smtp.mailtrap.io"
  EMAIL_PORT: "2525"
  EMAIL_USER: "830d7fcbdcbcc3"
  EMAIL_PASS: "b105b1e399cb89"
  EMAIL_FROM: "Chatterly Support <noreply@chatterly.dev>"
  # SMS/Twilio Configuration
  TWILIO_ACCOUNT_SSID: "AC2e7e6f7af36439077f1594e6ba488e42"
  TWILIO_AUTH_TOKEN: "cdadfd7ee4bde97c3cf3026b4e6a603a"
  TWILIO_PHONE_NUMBER: "+923035215727"
  TWILIO_RECOVERY_NUMBER: "78UHGDE25L9CBCVQJB5KGBE4"
