# Rules of Thumb for this File:
#   1. Never commit real values to Git
#   2. Encode Values:  echo -n "my-secret-value" | base64
#    3. Use placeholders for values in the file, and replace them with actual values during deployment using tools like Kustomize or Helm.
#   4. Apply manually once:  kubectl apply -f secret.yaml or better use Azure Key Vault and External
#   5. This file is a TEMPLATE. In production, secrets come from Azure Key Vault via the CSI driver -not hardcoded here.

apiVersion: v1
kind: Secret

metadata:
  name: chatterly-secrets
  namespace: chatterly-dev
type: Opaque
data:
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cG9zdGdyZXM="

  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXN2Yzo1NDMyL2NoYXR0ZXJseQ=="
  REDIS_URL: "cmVkaXM6Ly9yZWRpcy1zdmM6NjM3OQ=="

  JWT_ACCESS_SECRET: "YmMxYTk5MmM2MmRiYjNlMjVlZjk5N2QzOTBlNTZmY2Q0OTBlZjgyNTkxYTU0MjU3ZTViNGY0YWVjMjMwOWM3ZjgwYzYyODE2YWJmZjE3MjVkNTMyYTYzYjc5ZWQ5YWQyMTVjMTE0NGM0YTRlNzA3NTc4ZGQxMzcyOTBlYjdiNzk="

  JWT_REFRESH_SECRET: "NjQyODhjMTliOTM4MjliZjRlNTdhZjJkZDA5ZjY1NjAzYzBiZGQzZTUzYjFhYmNkNWEwNWU0NTQ2MGQ3MjIzYmIzY2E5MzQ0MmQyMzA1NDNjMTBmMmZmNjljYmIxOGZiODA2M2M4OGFmZWQzZmM5NTBhMGZlYjg3MmQ4YzhkOWY="

  EMAIL_USER: "ODMwZDdmY2JkY2JjYzM="

  EMAIL_PASS: "YjEwNWIxZTM5OWNiODk="

  TWILIO_ACCOUNT_SSID: "QUMyZTdlNmY3YWYzNjQzOTA3N2YxNTk0ZTZiYTQ4OGU0Mg=="

  TWILIO_AUTH_TOKEN: "Y2RhZGZkN2VlNGJkZTk3YzNjZjMwMjZiNGU2YTYwM2E="

  TWILIO_RECOVERY_NUMBER: "NzhVSEdERTI1TDlDQkNWUUpCNUtHQkU0"
