# Rules of Thumb for this File:
#   1. Never commit real values to Git
#   2. Encode Values:  echo -n "my-secret-value" | base64
#    3. Use placeholders for values in the file, and replace them with actual values during deployment using tools like Kustomize or Helm.
#   4. Apply manually once:  kubectl apply -f secret.yaml or better use Azure Key Vault and External
#   5. This file is a TEMPLATE. In production, secrets come from Azure Key Vault via the CSI driver -not hardcoded here.

apiVersion: v1
kind: Secret

metadata:
  name: chatterly-secrets
  namespace: chatterly-dev
type: Opaque
data:
  POSTGRES_USER: "UE9TVEdSRVNfVVNFUg=="
  POSTGRES_PASSWORD: "UE9TVEdSRVNfUEFTU1dPUkQ="

  DATABASE_URL: "REFUQUJBU0VfVVJM"
  JWT_SECRET: "SldUX1NFQ1JFVA=="
  # REDIS_PASSWORD: "UkVESVNfUEFTU1dPUkQ="
